topoguidebaptisteheng/itineraires/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /itineraires/
    path('', views.liste_itineraires, name='liste_itineraires'),
    
    # ex: /itineraires/1/
    path('<int:itineraire_id>/', views.details_itineraire, name = 'details_itineraire'),
    
    # ex: /itineraires/1/2/
    path('<int:itineraire_id>/<int:sortie_id>/', views.details_sortie, name = 'details_sortie'),
    
    # ex: /itineraires/nouvelle_sortie/
    path('nouvelle_sortie/', views.nouvelle_sortie, name = 'nouvelle_sortie'),
    
    # ex: /itineraires/modif_sortie/13/
    path('modif_sortie/<int:sortie_id>/', views.modif_sortie, name = 'modif_sortie'),
    
    # ex: /itineraires/accounts/login/
    path('accounts/login/', views.login_view, name = 'login_view'),
    
    # ex: /itineraires/accounts/logout
    path('accounts/logout/', views.logout_view, name = 'logout_view')
]

topoguidebaptisteheng/topoguidebaptisteheng/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('itineraires/', include('itineraires.urls')),
    path('admin/', admin.site.urls),
]

topoguidebaptisteheng/itineraires/models.py
from django.db import models
from django.contrib.auth.models import User

class Itineraire(models.Model):
    """ 
    Un itinéraire, crée par l'admin
    """
    titre = models.CharField(max_length=200)
    point_de_depart = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)
    alt_depart = models.FloatField('Altitude (m)') 
    alt_min = models.FloatField('Altitude minimale (m)') 
    alt_max = models.FloatField('Altitude maximale (m)') 
    deniv_pos_cumul = models.FloatField('Denivele positif cumule (m)') 
    deniv_neg_cumul = models.FloatField('Denivele negatif cumule (m)') 
    duree = models.IntegerField('Durée (h)')
    class NiveauxDifficulte(models.IntegerChoices):
        IMPOSSIBLE = 5
        EPUISANT = 4
        NORMAL = 3
        PROMENADE = 2
        REPOS = 1

    difficulte = models.IntegerField(choices=NiveauxDifficulte.choices)
    
    def __str__(self):
        return self.titre
    
class Sortie(models.Model):
    """
    Une sortie, modifiable par l'admin et l'utilisateur qui l'a créée
    """
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    
    #on relie un itinéraire à chaque sortie
    itineraire = models.ForeignKey('Itineraire', on_delete=models.CASCADE)
    date_sortie = models.DateTimeField('date sortie')

    duree = models.IntegerField('Durée (h)')
    nombre_personnes = models.IntegerField('Nombre de personnes')
    class NiveauxExperience(models.IntegerChoices):
        """
        Il s'agit des niveaux possibles d'un groupe de sportifs
        """
        DEBUTANTS = 1
        MIXTE = 2
        EXPERIMENTES = 3
        
    experience = models.IntegerField(choices=NiveauxExperience.choices)
    
    class Meteos(models.IntegerChoices):
        MAUVAISE = 1
        MOYENNE = 2
        BONNE = 3
    
    meteo = models.IntegerField(choices=Meteos.choices)
    
    class NiveauxDifficulte(models.IntegerChoices):
        IMPOSSIBLE = 5
        EPUISANT = 4
        NORMAL = 3
        PROMENADE = 2
        REPOS = 1
        
    difficulte =models.IntegerField(choices=NiveauxDifficulte.choices)

topoguidebaptisteheng/itineraires/forms.py
from django import forms
from .models import Sortie

class SortieForm(forms.ModelForm):
    """
    Formulaire de sortie, prenant en entrée les informations précisées dans sortie.models.py
    """
    class Meta :
        model = Sortie
        fields = '__all__' 

topoguidebaptisteheng/itineraires/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from .models import Itineraire, Sortie
from django.http import HttpResponse
from django.template import loader
from .forms import SortieForm
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm

def liste_itineraires(request):
    """Liste des itinéraires

    Args:
        request (GET) : Récupère la liste des itinéraires de la base de données

    Returns:
        - une page listant ces itinéraires
    """ 
    liste_itineraires = get_list_or_404(Itineraire)
    return render(request, 'itineraires/liste_itineraires.html', {'liste_itineraires': liste_itineraires})

def details_itineraire(request, itineraire_id):
    """Liste des sorties associées à un itinéraire

    Args:
        request (GET): Récupère l'itinéraire sur lequel on a cliqué sur la page d'accueil
        itineraire_id (database ID): ID associé à l'itinéraire dont on veut voir les sorties associées

    Returns:
        - une page listant les sorties associées à un itinéraire
    """
    itineraire = get_object_or_404(Itineraire, pk=itineraire_id)
    return render(request, 'itineraires/details_itineraire.html', {'itineraire': itineraire})
    
def details_sortie(request, itineraire_id, sortie_id):
    """Détails d'une sortie

    Args:
        request (GET): Récupère une sortie précise d'un sportif
        itineraire_id (database ID): ID associé à l'itinéraire
        sortie_id (database ID): ID associé à la sortie dont on veut voir les détails

    Returns:
        - une page listant les informations de l'itinéraire puis les détails du sportif sur sa propre sortie
    """
    
    sortie = get_object_or_404(Sortie, pk = sortie_id)
    
    
    return render(request, 'itineraires/details_sortie.html', {'sortie': sortie})


def nouvelle_sortie(request):
    """Bouton de nouvelle sortie, disponible seulement si l'utilisateur est connecté

    Args:
        request (GET ou POST): Récupère le form à remplir pour créer une nouvelle sortie, et le renvoie à la base de données

    Returns:
        - formulaire à remplir pour ajouter une sortie
    """
    if request.method == 'GET':
        form = SortieForm()
        
    elif request.method == 'POST':
        form = SortieForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('liste_itineraires')
    return render(request, 'itineraires/nouvelle_sortie.html', {'form': form})


def modif_sortie(request, sortie_id):
    """Bouton de modification de sortie, disponible seulement si l'utilisateur connecté est celui ayant effectué la sortie

    Args:
        request (GET ou POST): Récupère le form à remplir pour modifier la sortie, et le renvoie à la base de données
        sortie_id (ID database): On récupère les informations de la sortie à modifier

    Returns:
        - formulaire pré-remplit à modifier pour changer les informations d'une sortie
    """
    sortie = Sortie.objects.get(pk=sortie_id)
    if request.method == 'GET':
        form = SortieForm(instance=sortie)
    elif request.method == 'POST':
        form = SortieForm(request.POST, instance=sortie)
        if form.is_valid():
            form.save()
            return redirect('liste_itineraires')
    return render(request, 'itineraires/modif_sortie.html', {'form': form})


def login_view(request):
    """Connexion au site

    Args:
        request (POST): Récupère le form à remplir pour se connecter

    Returns:
        - une formulaire d'authentification à remplir pour se connecter
    """
    form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})

def logout_view(request):
    """Déconnexion du site

    Args:
        request (POST) : se déconnecte du site

    Returns:
        - retour à la page d'accueil, l'utilisateur n'est plus connecté
    """
    logout(request)
    return liste_itineraires(request)

topoguidebaptisteheng/itineraires/templates/itineraires/details_itineraire.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'itineraires/style.css' %}">

<h1>
{% block title %}Liste des sorties au {{ itineraire.titre }} {% endblock title%}
</h1>

{% block content %}

<div class="row">
    <table class="table table-striped">

        <thead>
        <tr>
            {# Titres des informations essentielles de l'itinéraire#}
            <th>Altitude de départ</th>
            <th>Altitude minimale</th>
            <th>Altitude maximale</th>
            <th>Dénivelé positif cumulé</th>
            <th>Dénivelé negatif cumulé</th>
            <th>Durée estimée</th>
            <th>Difficulté estimée</th>
        </tr>
        </thead>

            <tbody>
                    <tr>
                    {# Informations essentielles de l'itinéraire #}
                    <td>{{ itineraire.point_de_depart }}</td>
                    <td>{{itineraire.alt_min}}</td>
                    <td>{{itineraire.alt_max}}</td>
                    <td>{{itineraire.deniv_pos_cumul}}</td>
                    <td>{{itineraire.deniv_neg_cumul}}</td>
                    <td>{{itineraire.duree}}</td>
                    <td>{{itineraire.difficulte}}</td>
                    </tr>
                </tbody>    

        <thead>
        <tr>
            {# Titres des informations essentielles concernant les sorties associées à l'itinéraire#}
            <th>Par </th>
            <th>Date</th>
            <th>Details</th>
        </tr>
        </thead>

        <tbody>
            {# Affiche les informations essentielles concernant les sorties  #}
            {% for sortie in itineraire.sortie_set.all %}
            <tr>
            <td>{{ sortie.utilisateur.username }}</td> 
            <td>{{ sortie.date_sortie}}</td>

            {# Affiche le lien vers tous les détails précis de la sortie#}
            <td><li><a href="/itineraires/{{ itineraire.id }}/{{ sortie.id }}/"> Consulter </a></li></td>

            {# Fait apparaitre le bouton si l'utilisateur connecté est bien celui qui a enregistré la sortie#}
            {% if request.user == sortie.utilisateur %}   
                <td><li><a href="/itineraires/modif_sortie/{{ sortie.id }}/"> Modifier </a></li></td>
            {% endif  %}
            </tr>
            {% endfor %}
        </tbody>

        <tbody>
            <tr>
            {# Fait apparaitre le bouton Nouvelle Sortie seulement si l'utilisateur est connecté#}
            {% if request.user.is_authenticated %}  
                <td><li><a href="/itineraires/nouvelle_sortie/"> Nouvelle sortie </a></li></td>
            {% endif  %}
            </tr>
        </tbody>

        <tbody>
            {# Si l'utilisateur n'est pas connecté, le bouton de connexion apparait #}
            {% if request.user.is_authenticated != True %}  
                <td><li><a href="/itineraires/accounts/login/"> Connexion </a></li></td>
            {% endif  %}    

            {# Si l'utilisateur est connecté, le bouton de déconnexion apparait#}
            {% if request.user.is_authenticated %}  
                <td><li><a href="/itineraires/accounts/logout/"> Déconnexion </a></li></td>
            {% endif  %}
        </tbody>

        <tbody>
            <tr>
            {#Bouton de retour à la liste des itinéraires#}
            <td><li><a href="/itineraires/"> >>> Retour à la liste des itinéraires </a></li></td>
            </tr>
        </tbody>

    </table>
</div>


{% endblock content %}

topoguidebaptisteheng/itineraires/templates/itineraires/details_sortie.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'itineraires/style.css' %}">

<h1>
{% block title %}Informations sur la sortie de {{ sortie.utilisateur.username }} au {{ sortie.itineraire.titre }} {% endblock title%}
</h1>

{% block content %}

<div class="row">
    <table class="table table-striped">

        <thead>
        <tr>
            {#Titres des informations essentielles sur la sortie d'un utilisateur #}
            <th>Date </th>
            <th>Durée réelle</th>
            <th>Nombre de participants </th>
            <th>Type de randonneurs </th>
            <th>Météo </th>
            <th>Difficulté ressentie </th>
        </tr>
        </thead>

        <tbody>
        <tr>
            {#Informations essentielles sur la sortie de l'utilisateur #}
            <td>{{ sortie.date_sortie }}</td>
            <td>{{ sortie.duree}}</td>
            <td>{{ sortie.nombre_personnes}}</td>
            <td>{{ sortie.experience}}</td>
            <td>{{ sortie.meteo}}</td>
            <td>{{ sortie.difficulte}}</td>  
        </tr>
        </tbody>

    </table>
</div>


{% endblock content %}

topoguidebaptisteheng/itineraires/templates/itineraires/liste_itineraires.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'itineraires/style.css' %}">

<h1>
{% block title %}Itineraires {% endblock title%}
</h1>

{% block content %}

<div class="row pb-3">
    <h2>{{ Itineraire.titre }}</h2>
</div>

<div class="row">
    <table class="table table-striped">

        <thead>
        <tr>
            {#Titres des informations essentielles d'un itinéraire #}
            <th>Nom</th>
            <th>Durée estimée (h)</th>
            <th>Difficulté estimée (sur 5) </th>
        </tr>
        </thead>

        <tbody>
        
        {# Pour chaque itinéraire, on rend les informations essentielles #}
        {% for itineraire in liste_itineraires %}
            <tr>
            <td><li><a href="/itineraires/{{ itineraire.id }}/">{{ itineraire.titre }}</a></li></td>
            <td>{{ itineraire.duree }}</td>
            <td>{{ itineraire.difficulte }}</td>

            </tr>
        {% endfor %}
        </tbody>
        
        <tbody>
            {# Si l'utilisateur n'est pas connecté, le bouton de connexion apparait #}
            {% if request.user.is_authenticated != True %}  
                <td><li><a href="/itineraires/accounts/login/"> Connexion </a></li></td>
            {% endif  %}    

            {# Si l'utilisateur est connecté, le bouton de déconnexion apparait #}
            {% if request.user.is_authenticated %}  
                <td><li><a href="/itineraires/accounts/logout/"> Déconnexion </a></li></td>
            {% endif  %}
        </tbody>

    </table>
</div>


{% endblock content %}

topoguidebaptisteheng/itineraires/templates/itineraires/modif_sortie.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'itineraires/style.css' %}">

<h1>
{% block title %}Modification sortie{% endblock title%}
</h1>

{% block content %}

<form action="{% url 'modif_sortie' form.instance.id %}" method="post">
    {% csrf_token %}
    
    {# Rend un form de Sortie pour modifier une sortie existante#}
    {{form}}
    <input type = "submit"> Modification </button>
</form>

{# En cas d'annulation, on revient à la page principale #}
<tbody>
    <td><li><a href="/itineraires/"> Annuler </a></li></td>
</tbody>

{% endblock content %}

topoguidebaptisteheng/itineraires/templates/itineraires/nouvelle_sortie.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'itineraires/style.css' %}">

<h1>
{% block title %}Creation nouvelle sortie{% endblock title%}
</h1>

{% block content %}

<form action="{% url 'nouvelle_sortie' %}" method="post" >
    {% csrf_token %}
    
    {# Rend un form de Sortie pour entrer une nouvelle sortie#}
    {{form}}
    <input type = "submit"> Ajouter </button>
</form>

{# En cas d'annulation, on revient à la page principale #}
<tbody>
    <td><li><a href="/itineraires/"> Annuler </a></li></td>
</tbody>


{% endblock content %}